name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    # Checkout repository
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0

    - name: Publish .NET Core Project
      run: dotnet publish RyanTT.csproj -o release

    - name: Commit output directory to GitHub Pages branch "gh-pages"
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot